apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
    - name: delve
      port: 2345
      targetPort: delve
      nodePort: 32345
  selector:
    app: {{ template "fullname" . }}
  # debugging might work better with sesssion affinity
  sessionAffinity: ClientIP