apiVersion: v1
kind: Pod
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    component: webapp-go
spec:
  containers:
    - name: {{ template "fullname" . }}
      image: "webapp-go:latest"
      imagePullPolicy: Never
      ports:
        - name: http
          containerPort: 8080
        - name: delve
          containerPort: 2345